---
title: "iLevel Calculations"
author: "NAVEX, Inc."
date: "`r Sys.Date()`"
params:
  

---

# Setup
```{r setup, include=FALSE}
# CRAN Packages
suppressPackageStartupMessages({
  library(data.table)
  library(tidyverse)
  library(salesforcer)
  library(yaml)
  library(rlang)
  library(lubridate)
  library(openxlsx)
  library(readxl)
})

auth <- yaml.load_file("secrets.yml")
config <- yaml.load_file("config.yml")
```

# Queries
```{r query}

from_date <- config$from_date
to_date <- config$to_date

## Strings
  # issues

arr_risk_query <- "SELECT
                    Id,
                    AccountName__c,
                    Issue_Type__c,
                    Active_Recurring_Revenue__c,
                    Product_Family__c,
                    AccountName__r.Reporting_Region__c,
                    Issue_Owner__r.Location__c,
                    Name,
                    Date_Reported__c
                  FROM
                    Issue__c
                  WHERE
                    AccountName__r.Test_Account__c = FALSE
                    AND Status__c IN ('Unresolved', 'Open - Health Data Action', 'Open - Unresolved')
                    AND Issue_Type__c IN ('Red', 'Yellow')"

issues_query <- paste0("SELECT
                    Id,
                    AccountName__c,
                    Issue_Type__c,
                    Active_Recurring_Revenue__c,
                    Product_Family__c,
                    Name,
                    Date_Reported__c,
                    Date_Closed__c,
                    Issue_Owner__r.Location__c,
                    Status__c
                  FROM
                    Issue__c
                  WHERE
                    AccountName__r.Test_Account__c = FALSE
                    AND Issue_Type__c IN ('Red', 'Yellow')
                    AND ((Date_Reported__c >= ", from_date, "
                    AND Date_Reported__c <= ", to_date, ")
                      OR (Date_Closed__c >= ", from_date, "
                        AND Date_Closed__c <=", to_date, "))")
                  
nps_query <- paste("SELECT 
        AccountId,
        Survey_Completed__c,
        NPS_Overall_Client_Category__c,
        Reason_Code__c,
        NPS_Product__c,
        NPS_Score__c,
        Account__r.Name,
        Account__r.CurrencyIsoCode,
        Account__r.Total_Asset_ARR__c,
        Account__r.Owner.Name,
        Account__r.Reporting_Region__c 
      FROM 
        NPS_Survey_Results__c 
      WHERE 
        AccountId != null 
        AND Account__r.Test_Account__c = FALSE 
        AND Survey_Completed__c >= ", from_date, " 
        AND Survey_Completed__c <= ", to_date, "")

qualified_leads_query <- paste("SELECT
                    Opportunity.Id,
                    Opportunity.AccountId,
                    Opportunity.Name,
                    Opportunity.Services_Referred_By_Users__c,
                    Opportunity.Services_Lead_Source__c,
                    TotalPrice,
                    Opportunity.Probability,
                    Opportunity.CloseDate,
                    Opportunity.StageName,
                    Opportunity.Proposed_Product__c,
                    Opportunity.Currency_Conversion_Rate_at_Close__c,
                    Opportunity.Account.Name,
                    Opportunity.Account.CurrencyIsoCode,
                    Opportunity.Account.Total_Asset_ARR__c,
                    Opportunity.Account.Owner.Name,
                    Opportunity.Services_Referred_By_Users__r.Location__c,
                    Opportunity.Services_Referred_By_Users__r.Group__c,
                    Opportunity.SQL_Date_FCI__c
                    FROM
                      OpportunityLineItem
                    WHERE
                      Cross_Sell_Classification__c IN ('Upsell', 'Cross-sell', 'New')
                      AND Include_In_Pipeline__c = TRUE
                      AND Opportunity.AccountId != null
                      AND Opportunity.Amount > 0
                      AND Opportunity.ARR_Net__c > 0
                      AND Opportunity.Account.Test_Account__c = FALSE
                      AND Opportunity.Order_Sub_Type__c != 'Multi-Account Transaction (MAT)'
                      AND Opportunity.Services_Lead_Source__c = 'Up Sell'
                      AND Opportunity.Services_Referred_By_Users__r.Group__c IN ('Customer Success Managers', 'Customer Support', 'Implementation', 'Professional Services')
                      AND Opportunity.SQL_Date_FCI__c >= ", from_date, "
                      AND Opportunity.SQL_Date_FCI__c <= ", to_date)

surveys_query <- paste("SELECT 
        X18_Digit_AccountId__c, 
        Survey_Completed__c, 
        Team__c, 
        Project_Primary_Product__c,
        Delivery_Survey_Type__c,
        Q1_Technician_Assist__c, 
        Q4_Product_Satisfaction__c, 
        Imp_Comp_q3__c, 
        PS_Comp_q3__c, 
        PS_OnSite_q4__c, 
        Account__r.Name, 
        Account__r.Total_Asset_ARR__c, 
        Account__r.Owner.Name,
        Account__r.Owner.Sales_Rep_Role__c,
        PSE_Project__r.pse__Project_Manager__r.pse__Region__r.Name,
        Case__r.Owner__r.Location__c,
        Case__r.Owner__r.Name, 
        Case__r.Owner__r.Manager.Name
      FROM 
        Survey_Results__c 
      WHERE 
        (X18_Digit_AccountId__c != null 
        AND Account__r.Test_Account__c = FALSE 
        AND Exclude_from_Reporting__c = FALSE 
        AND Survey_Completed__c >= ", from_date, " 
        AND Survey_Completed__c <= ", to_date, ") 
        AND (Q1_Technician_Assist__c != null 
        OR Q4_Product_Satisfaction__c != null 
        OR Imp_Comp_q2__c != null 
        OR PS_Comp_q3__c != null)")

proj_hours_sold_query <- paste0("SELECT
        Milestone_ID_18__c,
        Name,
        Product__r.GL_Group__c,
        Product__r.Family,
        pse__Status__c,
        Total_Planned_Hours__c,
        Milestone_PM__r.Name,
        Milestone_PM__r.pse__Group__r.Name,
        Milestone_PM__r.pse__Region__r.Name,
        Milestone_PM_s_Manager__r.Name,
        Account__r.Reporting_Region__c,
        pse__Project__r.pse__Opportunity__r.CloseDate,
        CreatedDate
      FROM
        pse__Milestone__c
      WHERE
        Account__r.Test_Account__c = FALSE
        AND Product__r.Family IN (
          'AlertLine',
          'Disclosure Management',
          'EP Hotline',
          'EP Incident Management',
          'ESG',
          'GRC Insights',
          'IntegriLink',
          'IRM',
          'Lockpath',
          'NG Compliance Training',
          'NG Gateway',
          'NG Policy Management',
          'RiskRate',
          'Suite Compliance Training',
          'Suite Hotline',
          'Suite Incident Management',
          'Suite Policy Management',
          'Suite Survey',
          'Telephony',
          'WhistleB')
        AND Product__r.GL_Group__c IN (
          'Other Services',
          'Required Setup',
          'Professional Services')
        AND pse__Project__r.pse__Is_Template__c = FALSE
        AND ((pse__Project__r.pse__Opportunity__r.CloseDate >= ", from_date, "
          AND pse__Project__r.pse__Opportunity__r.CloseDate <= ", to_date , ")
        OR (CreatedDate >= ", from_date, "T00:00:00Z 
          AND CreatedDate <= ", to_date, "T23:59:59Z 
          AND Name LIKE '%Course Swap%'))")

proj_hours_complete_query <- paste("SELECT
        Milestone_ID_18__c,
        Name,
        Product__r.GL_Group__c,
        Product__r.Family,
        pse__Status__c,
        Total_Planned_Hours__c,
        Planned_vs_Client_Billable_Hours__c,
        Milestone_PM__r.Name,
        Milestone_PM__r.pse__Group__r.Name,
        Milestone_PM__r.pse__Region__r.Name,
        Milestone_PM_s_Manager__r.Name,
        Account__r.Reporting_Region__c,
        Account__r.Account_Owner_Region_CSO_Reporting__c,
        Actual_Go_Live__c
      FROM
        pse__Milestone__c
      WHERE
        Account__r.Test_Account__c = FALSE
        AND pse__Status__c = 'Complete'
        AND Actual_Go_Live__c >= ", from_date, "
        AND Actual_Go_Live__c <= ", to_date , "
        AND (Planned_vs_Billable_Hours_Last_Month__c > 0
        OR Under_Planned_Hours_Last_Month__c > 0)
        AND Product__r.Family IN (
          'AlertLine',
          'Disclosure Management',
          'EP Hotline',
          'EP Incident Management',
          'ESG',
          'GRC Insights',
          'IntegriLink',
          'Lockpath',
          'NG Compliance Training',
          'NG Gateway',
          'NG Policy Management',
          'RiskRate',
          'Suite Compliance Training',
          'Suite Hotline',
          'Suite Incident Management',
          'Suite Policy Management',
          'Suite Survey',
          'Telephony',
          'WhistleB')
        AND Product__r.GL_Group__c IN (
          'Other Services',
          'Required Setup',
          'Professional Services')
        AND pse__Project__r.pse__Is_Template__c = FALSE")

proj_hours_overages_query <- paste("SELECT
        Milestone_ID_18__c,
        Name,
        Product__r.GL_Group__c,
        Product__r.Family,
        pse__Status__c,
        Total_Planned_Hours__c,
        Planned_vs_Client_Billable_Hours__c,
        Planned_Hours_Overages_Last_Month__c,
        Milestone_PM__r.Name,
        Milestone_PM__r.pse__Group__r.Name,
        Milestone_PM__r.pse__Region__r.Name,
        Milestone_PM_s_Manager__r.Name,
        Account__r.Reporting_Region__c,
        Account__r.Account_Owner_Region_CSO_Reporting__c,
        Actual_Go_Live__c
      FROM
        pse__Milestone__c
      WHERE
        Account__r.Test_Account__c = FALSE
        AND pse__Status__c = 'Complete'
        AND Planned_Hours_Overages_Last_Month__c > 0
        AND Product__r.Family IN (
          'AlertLine',
          'Disclosure Management',
          'EP Hotline',
          'EP Incident Management',
          'ESG',
          'GRC Insights',
          'IntegriLink',
          'NG Compliance Training',
          'NG Gateway',
          'NG Policy Management',
          'RiskRate',
          'Suite Compliance Training',
          'Suite Hotline',
          'Suite Incident Management',
          'Suite Policy Management',
          'Suite Survey',
          'Telephony',
          'WhistleB')
        AND Product__r.GL_Group__c IN (
          'Other Services',
          'Required Setup',
          'Professional Services')
        AND pse__Project__r.pse__Is_Template__c = FALSE
        AND pse__Project__r.pse__Group__r.Name IN ('Implementation', 'Professional Services')")

proj_hours_backlog_query <- paste("SELECT
        Milestone_ID_18__c,
        Name,
        Product__r.GL_Group__c,
        Product__r.Family,
        pse__Status__c,
        Total_Planned_Hours__c,
        Planned_vs_Client_Billable_no_neg__c,
        Planned_Hours_Overages_Last_Month__c,
        Milestone_PM__r.Name,
        Milestone_PM__r.pse__Group__r.Name,
        Milestone_PM__r.pse__Region__r.Name,
        Milestone_PM_s_Manager__r.Name,
        Account__r.Reporting_Region__c,
        Account__r.Account_Owner_Region_CSO_Reporting__c,
        Actual_Go_Live__c
      FROM
        pse__Milestone__c
      WHERE
        Account__r.Test_Account__c = FALSE
        AND pse__Status__c IN (
        'Active', 
        'Delayed Active',
        'Delayed On-Hold',
        'Not Started',
        'Pending Termination',
        'Pipeline')
        AND Product__r.Family IN (
          'AlertLine',
          'Disclosure Management',
          'EP Hotline',
          'EP Incident Management',
          'ESG',
          'GRC Insights',
          'IntegriLink',
          'NG Compliance Training',
          'NG Gateway',
          'NG Policy Management',
          'RiskRate',
          'Suite Compliance Training',
          'Suite Hotline',
          'Suite Incident Management',
          'Suite Policy Management',
          'Suite Survey',
          'Telephony',
          'WhistleB')
        AND Product__r.GL_Group__c IN (
          'Other Services',
          'Required Setup',
          'Professional Services')
        AND pse__Project__r.pse__Is_Template__c = FALSE
        AND pse__Project__r.pse__Group__r.Name IN ('Implementation', 'Professional Services')")

on_time_completion_query <- paste("SELECT
        Milestone_ID_18__c,
        Name,
        pse__Project__r.pse__Group__r.Name,
        Product__r.Family,
        pse__Status__c,
        Total_Planned_Hours__c,
        pse__Planned_Hours__c,
        Total_Approved_Hours__c,
        Planned_vs_Client_Billable_Hours__c,
        Milestone_On_Time_TD__c,
        Calculated_Duration_days__c,
        Milestone_PM__r.Name,
        Milestone_PM__r.pse__Group__r.Name,
        Milestone_PM__r.pse__Region__r.Name,
        Milestone_PM_s_Manager__r.Name,
        Account__r.Reporting_Region__c,
        Account__r.Account_Owner_Region_CSO_Reporting__c,
        Actual_Go_Live__c
      FROM
        pse__Milestone__c
      WHERE
        Account__r.Test_Account__c = FALSE
        AND pse__Status__c = 'Complete'
        AND pse__Project__r.pse__Project_Status__c != 'Terminated'
        AND Actual_Go_Live__c >= ", from_date, "
        AND Actual_Go_Live__c <= ", to_date, "
        AND pse__Project__r.pse__Group__r.Name IN ('Professional Services', 'Implementation')
        AND Product__r.Family IN (
          'AlertLine',
          'Disclosure Management',
          'EP Hotline',
          'EP Incident Management',
          'ESG',
          'GRC Insights',
          'IntegriLink',
          'Lockpath',
          'NG Compliance Training',
          'NG Gateway',
          'NG Policy Management',
          'RiskRate',
          'Suite Compliance Training',
          'Suite Hotline',
          'Suite Incident Management',
          'Suite Policy Management',
          'Suite Survey',
          'Telephony',
          'WhistleB')")

cases_query <- paste0("SELECT Id,
                      Client_Care_Team__c,
                      Age_Days__c,
                      Skill__c,
                      Record_Type__c,
                      CreatedDate,
                      ClosedDate,
                      Account.Reporting_Region__c,
                      Owner__r.Name,
                      Owner__r.Location__c
                      FROM
                      Case
                      WHERE
                             Record_Type__c IN ('Customer Support Requests', 'Discontinued Client')
                             AND Status != 'Duplicate'
                             AND (Account.Test_Account__c = FALSE OR Account.Id = '0015000000iMvunAAC')
                             AND Client_Care_Team__c != 'NetClaim'
                             AND ((CreatedDate >= ", from_date, "T00:00:00Z AND CreatedDate <= ", to_date, "T00:00:00Z)
                              OR(ClosedDate >= ", from_date, "T00:00:00Z AND ClosedDate <= ", to_date, "T00:00:00Z))"
                      )

cases_backlog_query <- ("SELECT Id,
                      Client_Care_Team__c,
                      Age_Days__c,
                      Skill__c,
                      Record_Type__c,
                      CreatedDate,
                      ClosedDate,
                      Account.Reporting_Region__c,
                      Owner__r.Name,
                      Owner__r.Location__c
                      FROM
                      Case
                      WHERE
                            Record_Type__c IN ('Customer Support Requests')
                            AND Status != 'Duplicate'
                            AND (Account.Test_Account__c = FALSE OR Account.Id = '0015000000iMvunAAC')
                            AND Client_Care_Team__c != 'NetClaim'
                            AND Skill__c != 'RiskRate - Renewals'
                            AND Defect_Enhancement__c = FALSE
                            AND IsClosed = FALSE
                      ")

cases_milestones_query <- paste0("SELECT Id,
                       Case.Id,
                       ElapsedTimeInHrs,
                       ElapsedTimeInDays,
                       MilestoneType.Name,
                       Case.Client_Care_Team__c,
                       Case.Skill__c,
                       Case.Account.Reporting_Region__c,
                       Case.ClosedDate,
                       Case.Owner__r.Name,
                       Case.Owner__r.Location__c,
                       Case.Account.Customer_Success_Account__c
                       FROM
                       CaseMilestone
                       WHERE
                             MilestoneType.Name LIKE '%Resolution%'
                             AND Case.Record_Type__c = 'Customer Support Requests'
                             AND Case.Status != 'Duplicate'
                             AND Case.Defect_Enhancement__c = FALSE
                             AND Case.ClosedDate >= ", from_date, "T00:00:00Z
                             AND Case.Skill__c != 'RiskRate - Renewals'
                             AND Case.Account.Test_Account__c = FALSE")


utilization_query <- paste("SELECT
        Utilization_Calculation_Name__c,
        pse__Historical_Start_Date__c,
        pse__Historical_End_Date__c,
        pse__Utilization_Calculation__r.pse__Time_Period_Types__c,
        pse__Historical_Utilization__c,
        pse__Historical_Utilization_Billable_Only__c,
        pse__Historical_Calendar_Hours__c,
        pse__Historical_Billable_Hours__c,
        Historical_Client_Non_Billable__c,
        pse__Historical_Non_Billable_Hours__c,
        pse__Resource__r.Name,
        pse__Resource__r.pse__Salesforce_User__r.Manager.Name,
        pse__Resource__r.pse__Region__r.Name,
        pse__Resource__r.pse__Group__r.Name,
        pse__Resource__r.pse__Start_Date__c
      FROM
        pse__Utilization_Detail__c
      WHERE
          pse__Historical_Utilization_Billable_Only__c > 0
          AND pse__Historical_Start_Date__c = ", from_date, "
          AND pse__Utilization_Calculation__r.pse__Time_Period_Types__c = 'Month'
          AND pse__Resource__r.pse__Start_Date__c <= ", Sys.Date(), "
          AND pse__Resource__r.pse__Group__r.Name IN (
            'Implementation',
            'Professional Services',
            'Customer Support',
            'Customer Interface',
            'Technical Specialist',
            'Telecom',
            'Quality Assurance',
            'Lockpath - CS',
            'Lockpath - IS',
            'Lockpath - PS',
            'WhistleB - CS',
            'WhistleB - IS',
            'WhistleB - PS')")

util_pto_query <- paste("SELECT
        pse__Start_Date__c,
        pse__End_Date__c,
        pse__Status__c,
        pse__Total_Hours__c,
        pse__Milestone__r.Name,
        pse__Resource__r.Full_Name__c,
        pse__Resource__r.pse__Salesforce_User__r.Manager.Name,
        pse__Resource__r.pse__Group__r.Name
      FROM
        pse__Timecard__c
      WHERE
        pse__Milestone__r.Name = 'Time Off'
        AND pse__Status__c = 'Approved'
        AND pse__Resource__r.pse__Exclude_From_Time_Calculations__c = FALSE
        AND pse__Start_Date__c >= ", from_date, "
        AND pse__Start_Date__c <= ", to_date, "
        AND pse__Resource__r.pse__Group__r.Name IN (
          'Implementation',
          'Professional Services',
          'Customer Support',
          'Customer Interface',
          'Technical Specialist',
          'Telecom',
          'Quality Assurance',
          'Lockpath - CS',
          'Lockpath - IS',
          'Lockpath - PS',
          'WhistleB - CS',
          'WhistleB - IS',
          'WhistleB - PS')")

## Queries
sf_auth(username = auth$username, password = auth$password, security_token = auth$security_token)
arr_risk <- sf_query(arr_risk_query)
issues <- sf_query(issues_query)
qlb <- sf_query(qualified_leads_query)
surveys <- sf_query(surveys_query)
proj_hours_sold <- sf_query(proj_hours_sold_query)
proj_hours_complete <- sf_query(proj_hours_complete_query)
proj_hours_overages <- sf_query(proj_hours_overages_query)
proj_hours_backlog <- sf_query(proj_hours_backlog_query)
on_time_completion <- sf_query(on_time_completion_query)
cases <- sf_query(cases_query)
cases_backlog <- sf_query(cases_backlog_query)
cases_milestones <- sf_query(cases_milestones_query)
util <- sf_query(utilization_query)
util_pto <- sf_query(util_pto_query)

```

# Calculations
```{r arr_risk}
# issue\
arr_calcs_core <- arr_risk %>%
  group_by(Issue_Type__c, AccountName__c) %>% 
  filter(!Product_Family__c %in% c('Lockpath', 'IRM', 'NetClaim')) %>% 
  reframe(
    Issue_Count = n(),
    ARR_at_Risk = mean(Active_Recurring_Revenue__c)
  ) %>%
  bind_rows(arr_risk %>%
              filter(!Product_Family__c %in% c('Lockpath', 'IRM', 'NetClaim')) %>% 
              group_by(Issue_Type__c = "Total", AccountName__c) %>% 
              reframe(
                Issue_Count = n(),
                ARR_at_Risk = mean(Active_Recurring_Revenue__c)
               )
             ) %>% 
  group_by(Issue_Type__c) %>% 
  reframe(
    Issue_Count = sum(Issue_Count),
    ARR_at_Risk = sum(ARR_at_Risk)
  ) %>% 
  arrange(Issue_Type__c) %>% 
  bind_cols(
    issue_calcs <- arr_risk %>% 
              filter(!Product_Family__c %in% c('Lockpath', 'IRM', 'NetClaim')) %>% 
              group_by(Issue_Type__c) %>%
              summarize(
                `Customers at Risk` = n_distinct(AccountName__c)
                ) %>% 
      bind_rows(
        arr_risk %>%
          filter(!Product_Family__c %in% c('Lockpath', 'IRM', 'NetClaim')) %>% 
          summarize(
            `Issue_Type__c` = "Total",
            `Customers at Risk` = n_distinct(AccountName__c)
          )
      ) %>% 
      arrange(Issue_Type__c) %>% 
      select(`Customers at Risk`)
  ) %>%  
  arrange(Issue_Count)

arr_calcs_na <- arr_risk %>% 
  filter(AccountName__r.Reporting_Region__c == "AMER") %>%
  group_by(Issue_Type__c, AccountName__c) %>% 
  reframe(
    Issue_Count = n(),
    ARR_at_Risk = mean(Active_Recurring_Revenue__c)
  ) %>%
  bind_rows(arr_risk %>%
              filter(AccountName__r.Reporting_Region__c == "AMER") %>% 
              group_by(Issue_Type__c = "Total", AccountName__c) %>% 
              reframe(
                Issue_Count = n(),
                ARR_at_Risk = mean(Active_Recurring_Revenue__c)
               )
             ) %>% 
  group_by(Issue_Type__c) %>% 
  reframe(
    Issue_Count = sum(Issue_Count),
    ARR_at_Risk = sum(ARR_at_Risk)
  ) %>% 
  arrange(Issue_Type__c) %>% 
  bind_cols(
    issue_calcs <- arr_risk %>% 
              filter(AccountName__r.Reporting_Region__c == "AMER") %>% 
              group_by(Issue_Type__c) %>%
              summarize(
                `Customers at Risk` = n_distinct(AccountName__c)
                ) %>% 
      bind_rows(
        arr_risk %>%
          filter(AccountName__r.Reporting_Region__c == "AMER") %>% 
          summarize(
            `Issue_Type__c` = "Total",
            `Customers at Risk` = n_distinct(AccountName__c)
          )
      ) %>% 
      arrange(Issue_Type__c) %>% 
      select(`Customers at Risk`)
  ) %>% 
  arrange(Issue_Count) %>% 
  mutate(Issue_Type__c = str_c(Issue_Type__c, " - AMER"))

arr_calcs_int <- arr_risk %>% 
  filter(AccountName__r.Reporting_Region__c == "EMEA/APJ") %>%
  group_by(Issue_Type__c, AccountName__c) %>% 
  reframe(
    Issue_Count = n(),
    ARR_at_Risk = mean(Active_Recurring_Revenue__c)
  ) %>%
  bind_rows(arr_risk %>%
              filter(AccountName__r.Reporting_Region__c == "EMEA/APJ") %>% 
              group_by(Issue_Type__c = "Total", AccountName__c) %>% 
              reframe(
                Issue_Count = n(),
                ARR_at_Risk = mean(Active_Recurring_Revenue__c)
               )
             ) %>% 
  group_by(Issue_Type__c) %>% 
  reframe(
    Issue_Count = sum(Issue_Count),
    ARR_at_Risk = sum(ARR_at_Risk)
  ) %>% 
  arrange(Issue_Type__c) %>% 
  bind_cols(
    issue_calcs <- arr_risk %>% 
              filter(AccountName__r.Reporting_Region__c == "EMEA/APJ") %>% 
              group_by(Issue_Type__c) %>%
              summarize(
                `Customers at Risk` = n_distinct(AccountName__c)
                ) %>% 
      bind_rows(
        arr_risk %>%
          filter(AccountName__r.Reporting_Region__c == "EMEA/APJ") %>% 
          summarize(
            `Issue_Type__c` = "Total",
            `Customers at Risk` = n_distinct(AccountName__c)
          )
      ) %>% 
      arrange(Issue_Type__c) %>% 
      select(`Customers at Risk`)
  ) %>% 
  arrange(Issue_Count) %>% 
  mutate(Issue_Type__c = str_c(Issue_Type__c, " - EMEA/APJ"))

arr_calcs_lp <- arr_risk %>% 
  filter(Product_Family__c %in% c("Lockpath", "IRM") & Date_Reported__c < floor_date(Sys.Date(), unit = "month")) %>%
  group_by(Issue_Type__c, AccountName__c) %>% 
  reframe(
    Issue_Count = n(),
    ARR_at_Risk = mean(Active_Recurring_Revenue__c)
  ) %>%
  bind_rows(arr_risk %>%
              filter(Product_Family__c %in% c("Lockpath", "IRM")) %>% 
              group_by(Issue_Type__c = "Total", AccountName__c) %>% 
              reframe(
                Issue_Count = n(),
                ARR_at_Risk = mean(Active_Recurring_Revenue__c)
               )
             ) %>% 
  group_by(Issue_Type__c) %>% 
  reframe(
    Issue_Count = sum(Issue_Count),
    ARR_at_Risk = sum(ARR_at_Risk)
  ) %>% 
  arrange(Issue_Type__c) %>% 
  bind_cols(
    issue_calcs <- arr_risk %>% 
              filter(Product_Family__c %in% c("Lockpath", "IRM")) %>% 
              group_by(Issue_Type__c) %>%
              summarize(
                `Customers at Risk` = n_distinct(AccountName__c)
                ) %>% 
      bind_rows(
        arr_risk %>%
          filter(Product_Family__c %in% c("Lockpath", "IRM")) %>% 
          summarize(
            `Issue_Type__c` = "Total",
            `Customers at Risk` = n_distinct(AccountName__c)
          )
      ) %>% 
      arrange(Issue_Type__c) %>% 
      select(`Customers at Risk`)
  ) %>% 
  arrange(Issue_Count) %>% 
  mutate(Issue_Type__c = str_c(Issue_Type__c, " - IRM"))

arr_calcs_total <- arr_calcs_core %>% 
  bind_rows(arr_calcs_na) %>%
  bind_rows(arr_calcs_int) %>% 
  bind_rows(arr_calcs_lp)
```

```{r issues_opened/closed}
issues_pre <- issues %>% 
  rename(
    account_name = AccountName__c,
    ARR = Active_Recurring_Revenue__c,
    status = Status__c,
    type = Issue_Type__c,
    location = Issue_Owner__r.Location__c,
    product = Product_Family__c,
    date_reported = Date_Reported__c,
    date_closed = Date_Closed__c
  )

issues_opened <- issues_pre %>%
  filter(between(date_reported, as.Date(from_date), as.Date(to_date)),
        !product %in% "Lockpath") %>% 
  summarize(
    `Region` = "Core",
    `Opened` = n()
  ) %>% 
  bind_rows(issues_pre %>% 
              filter(between(date_reported, as.Date(from_date), as.Date(to_date)),
                     !product %in% c("Lockpath", "WhistleB"),
                     location %in% "US") %>%
              summarize(
                `Region` = "US",
                `Opened` = n()
              )
            ) %>% 
  bind_rows(issues_pre %>% 
              filter(between(date_reported, as.Date(from_date), as.Date(to_date)),
                     !product %in% "Lockpath",
                     location %in% "EU") %>%
              summarize(
                `Region` = "EU",
                `Opened` = n()
              )
            ) %>% 
  bind_rows(issues_pre %>% 
              filter(between(date_reported, as.Date(from_date), as.Date(to_date)),
                     !product %in% "Lockpath",
                     location %in% "India") %>%
              summarize(
                `Region` = "India",
                `Opened` = n()
              )
            ) %>% 
  bind_rows(issues_pre %>% 
              filter(between(date_reported, as.Date(from_date), as.Date(to_date)),
                     product %in% "Lockpath") %>%
              summarize(
                `Region` = "Lockpath",
                `Opened` = n()
              )
            )
```

```{r qualified_leads}
qlb_pre <- qlb %>% 
  rename(
    opportunity_id = Opportunity.Id,
    opportunity_name = Opportunity.Name,
    opportunity_referred_by = Opportunity.Services_Referred_by_Users__c,
    opportunity_referrer_group = Opportunity.Services_Referred_by_Users__r.Group__c,
    opportunity_referrer_location = Opportunity.Services_Referred_by_Users__r.Location__c,
    opportunity_source = Opportunity.Services_Lead_Source__c,
    opportunity_totalprice = TotalPrice,
    opportunity_sql_date = Opportunity.SQL_Date_FCI__c,
    opportunity_stage = Opportunity.StageName,
    opportunity_product = Opportunity.Proposed_Product__c,
    opportunity_conversion_rate = Opportunity.Currency_Conversion_Rate_at_Close__c,
    opportunity_probability = Opportunity.Probability,
    account_name = Opportunity.Account.Name,
    account_id = Opportunity.AccountId,
    account_currency_iso_code = Opportunity.Account.CurrencyIsoCode,
    total_asset_arr = Opportunity.Account.Total_Asset_ARR__c,
    account_owner = Opportunity.Account.Owner.Name
  ) %>% 
  mutate(
      total_asset_arr = as.double(total_asset_arr),
      opportunity_totalprice = as.double(opportunity_totalprice),
      opportunity_sql_date = as.Date(opportunity_sql_date),
      opportunity_conversion_rate = as.double(opportunity_conversion_rate),
      opportunity_amount_usd = round(opportunity_totalprice / opportunity_conversion_rate, 2)
    )

qlb_calc <- qlb_pre %>% 
  group_by(
    opportunity_referrer_group,
    opportunity_referrer_location
  ) %>% 
  summarize(
    value = round(sum(opportunity_amount_usd, na.rm = TRUE), 2),
    n = n_distinct(opportunity_id)
  ) %>%
  bind_rows(qlb_pre %>% filter(!opportunity_product %in% c("Lockpath", "WhistleB")) %>%
              mutate(opportunity_referrer_location = "Core") %>% 
              group_by(
                opportunity_referrer_group, opportunity_referrer_location
                ) %>% 
              summarize(
                value = round(sum(opportunity_amount_usd, na.rm = TRUE), 2),
                n = n_distinct(opportunity_id)
        )) 

```

```{r surveys}
surveys_pre <- surveys %>% 
  rename(
      account_id = X18_Digit_AccountId__c, 
      completed_date = Survey_Completed__c, 
      team = Team__c, 
      type = Delivery_Survey_Type__c,
      product = Project_Primary_Product__c,
      support_csat = Q1_Technician_Assist__c,
      product_csat = Q4_Product_Satisfaction__c, 
      imp_csat = Imp_Comp_q3__c, 
      ps_comp_csat = PS_Comp_q3__c, 
      account_name = Account__r.Name,
      total_asset_arr = Account__r.Total_Asset_ARR__c,
      account_owner = Account__r.Owner.Name,
      account_region = Account__r.Owner.Sales_Rep_Role__c,
      location = Case__r.Owner__r.Location__c,
      region = PSE_Project__r.pse__Project_Manager__r.pse__Region__r.Name,
      case_owner = Case__r.Owner__r.Name,
      case_owner_manager = Case__r.Owner__r.Manager.Name
    ) %>% 
    mutate(
      region = str_sub(region, 7, -1),
      completed_date = as.Date(completed_date),
      total_asset_arr = as.double(total_asset_arr),
      support_csat = as.double(support_csat),
      product_csat = as.double(product_csat),
      imp_csat = as.double(imp_csat),
      ps_comp_csat = as.double(ps_comp_csat),
      `AE Segment` = case_when(grepl("\\-F|\\-EAPJ", account_region) ~ sub("\\-F|\\-EAPJ", "", account_region),
                             grepl("\\-H", account_region) ~ "Hunter",
                             TRUE ~ account_region)
    )

csat_core <- surveys_pre %>%
  filter(!team %in% c("Lockpath"),
         !product %in% c("Lockpath")) %>% 
  group_by(`AE Segment`) %>% 
  summarize(
    `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
    `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
    `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
    `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
    Count = n()
  ) %>% 
  bind_rows(surveys_pre %>% filter(!team %in% c("Lockpath"),
                                   !product %in% c("Lockpath")) %>% 
           summarize(
             `AE Segment` = "Total",
             `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
             `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
             `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
             `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
             Count = n()
           ))
  
csat_us <- surveys_pre %>% 
  filter(location %in% "US"|region %in% "US",
         !team %in% "Lockpath",
         !product %in% c("Lockpath", "WhistleB")) %>% 
  group_by(`AE Segment`) %>% 
  summarize(
    `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
    `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
    `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
    `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
    Count = n()
  ) %>% 
  bind_rows(surveys_pre %>% filter(location %in% "US"|region %in% "US",
                                   !team %in% c("Lockpath"),
                                   !product %in% c("Lockpath", "WhistleB")) %>% 
           summarize(
             `AE Segment` = "Total",
             `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
             `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
             `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
             `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
             Count = n()
           ))

csat_eu <- surveys_pre %>% 
  filter(location %in% "EU"|region %in% "EU",
         !team %in% "Lockpath",
         !product %in% "Lockpath") %>% 
  group_by(`AE Segment`) %>% 
  summarize(
    `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
    `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
    `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
    `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
    Count = n()
  ) %>% 
  bind_rows(surveys_pre %>% filter(location %in% "EU"|region %in% "EU",
                                   !team %in% c("Lockpath"),
                                   !product %in% c("Lockpath")) %>% 
           summarize(
             `AE Segment` = "Total",
             `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
             `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
             `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
             `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
             Count = n()
           ))

csat_india <- surveys_pre %>%
  filter(location %in% "India"|region %in% "India",
         !team %in% "Lockpath",
         !product %in% "Lockpath") %>% 
  group_by(`AE Segment`) %>% 
  summarize(
    `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
    `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
    `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
    `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
    Count = n()
  ) %>% 
  bind_rows(surveys_pre %>% filter(location %in% "India"|region %in% "India",
                                   !team %in% c("Lockpath"),
                                   !product %in% c("Lockpath")) %>% 
           summarize(
             `AE Segment` = "Total",
             `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
             `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
             `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
             Count = n()
           ))

csat_irm <- surveys_pre %>% 
  filter(team %in% "Lockpath"|product %in% "Lockpath") %>% 
  group_by(`AE Segment`) %>% 
  summarize(
    `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
    `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
    `Implementation` = round(mean(imp_csat, na.rm = TRUE) * 10, 2),
    `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
    Count = n()
  ) %>% 
  bind_rows(surveys_pre %>% filter(team %in% "Lockpath"|product %in% "Lockpath") %>% 
           summarize(
             `AE Segment` = "Total",
             `Customer Support` = round(mean(support_csat, na.rm = TRUE) * 10, 2),
             `Product Satisfaction` = round(mean(product_csat, na.rm = TRUE) * 10, 2),
             `Professional Services` = round(mean(ps_comp_csat, na.rm = TRUE) * 10, 2),
             Count = n()
           ))
```

```{r project_hours}
proj_hours_sold <- proj_hours_sold %>%
  rename(
      milestone_id = Milestone_ID_18__c,
      milestone_name = Name,
      product_gl_group = Product__r.GL_Group__c,
      product_family = Product__r.Family,
      milestone_status = pse__Status__c,
      hours_sold = Total_Planned_Hours__c,
      milestone_pm = Milestone_PM__r.Name,
      milestone_pm_group = Milestone_PM__r.pse__Group__r.Name,
      milestone_pm_region = Milestone_PM__r.pse__Region__r.Name,
      milestone_pm_manager = Milestone_PM_s_Manager__r.Name,
      account_region = Account__r.Reporting_Region__c,
      opportunity_close_date = pse__Project__r.pse__Opportunity__r.CloseDate,
      created_date = CreatedDate
      ) %>% 
  mutate(
    group = case_when(
      product_gl_group %in% c("Required Setup", "Other Services") ~ "Implementation",
                      TRUE ~ as.character(product_gl_group))
  ) 
  #  %>% 
  #distinct(milestone_id, .keep_all = TRUE)

proj_hours_sold_core <- proj_hours_sold %>% 
  filter(
    !product_family %in% "Lockpath"
  ) %>% 
  group_by(group) %>% 
  summarize(
    hours_sold = round(sum(hours_sold, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_sold_na <- proj_hours_sold %>% 
  filter(
    !product_family %in% c("Lockpath", "WhistleB"),
    account_region == "AMER",
    opportunity_close_date >= from_date & opportunity_close_date <= to_date
  ) %>% 
  group_by(group) %>% 
  summarize(
    hours_sold = round(sum(hours_sold, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_sold_eu <- proj_hours_sold %>% 
  filter(
    !product_family %in% "Lockpath",
    account_region == "EMEA"
  ) %>% 
  group_by(group) %>% 
  summarize(
    hours_sold = round(sum(hours_sold, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_sold_india <- proj_hours_sold %>% 
  filter(
    milestone_pm_region == "NAVEX India"
  ) %>% 
  group_by(group) %>%
  summarize(
    hours_sold = round(sum(hours_sold, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_complete_pre <- proj_hours_complete %>% 
  rename(
      milestone_id = Milestone_ID_18__c,
      milestone_name = Name,
      product_gl_group = Product__r.GL_Group__c,
      product_family = Product__r.Family,
      milestone_status = pse__Status__c,
      hours_completed = Total_Planned_Hours__c,
      planned_hour_delta = Planned_vs_Client_Billable_Hours__c,
      milestone_pm = Milestone_PM__r.Name,
      milestone_pm_group = Milestone_PM__r.pse__Group__r.Name,
      milestone_pm_region = Milestone_PM__r.pse__Region__r.Name,
      milestone_pm_manager = Milestone_PM_s_Manager__r.Name,
      account_region = Account__r.Reporting_Region__c,
      go_live_date = Actual_Go_Live__c
    ) %>% 
  mutate(
      hours_completed = as.double(hours_completed),
      planned_hour_delta = as.double(planned_hour_delta),
      go_live_date = as.Date(go_live_date),
      hour_overages = if_else(planned_hour_delta < 0, abs(planned_hour_delta), 0),
      hours_saved = if_else(planned_hour_delta > 0, planned_hour_delta, 0),
      group = case_when(product_gl_group %in% c("Required Setup", "Other Services") ~ "Implementation",
                      TRUE ~ as.character(product_gl_group)),
      product = case_when((grepl("EP ", product_family)|product_family == "Telephony") ~ "EthicsPoint", grepl("Policy", product_family) ~ "PolicyTech", product_family == "NG Compliance Training" ~ "NAVEXEngage", product_family == "RiskRate" ~ "RiskRate", product_family == "WhistleB" ~ "WhistleB", product_family == "ESG" ~ "ESG", product_family == "Disclosure Manager" ~ "Disclosure Manager", product_family == "Lockpath" ~ "Lockpath")) %>% 
  distinct(milestone_id, .keep_all = TRUE) 

proj_hours_complete_core <- proj_hours_complete_pre %>% 
  filter(
    !product_family %in% "Lockpath"
  ) %>% 
  group_by(group, account_region) %>% 
  summarize(
    `total planned hours` = sum(hours_completed),
    n = n()
  ) %>% bind_rows(
    proj_hours_complete_pre %>% 
      filter(
        !product_family %in% "Lockpath"
      ) %>% 
      mutate(
        account_region = "Total"
      ) %>% 
      group_by(group, account_region) %>% 
      summarize(
        `total planned hours` = sum(hours_completed),
        n = n()
      )
  )

proj_hours_complete_india <- proj_hours_complete_pre %>% 
  filter(
    milestone_pm_region %in% "NAVEX India"
  ) %>% 
  group_by(group) %>% 
  summarize(
    `total planned hours` = sum(hours_completed),
    n = n()
  )

proj_hours_overages_pre <- proj_hours_overages %>% 
  rename(
      milestone_id = Milestone_ID_18__c,
      milestone_name = Name,
      product_gl_group = Product__r.GL_Group__c,
      product_family = Product__r.Family,
      milestone_status = pse__Status__c,
      hours_completed = Total_Planned_Hours__c,
      planned_hour_overages = Planned_Hours_Overages_Last_Month__c,
      planned_hour_delta = Planned_vs_Client_Billable_Hours__c,
      milestone_pm = Milestone_PM__r.Name,
      milestone_pm_group = Milestone_PM__r.pse__Group__r.Name,
      milestone_pm_region = Milestone_PM__r.pse__Region__r.Name,
      milestone_pm_manager = Milestone_PM_s_Manager__r.Name,
      account_cso_region_bad = Account__r.Account_Owner_Region_CSO_Reporting__c,
      account_region = Account__r.Reporting_Region__c,
      go_live_date = Actual_Go_Live__c
    ) %>% 
  mutate(
    hours_completed = as.double(hours_completed),
    planned_hour_delta = as.double(planned_hour_delta),
    go_live_date = as.Date(go_live_date),
    hour_overages = if_else(planned_hour_delta < 0, abs(planned_hour_delta), 0),
    hours_saved = if_else(planned_hour_delta > 0, planned_hour_delta, 0),
    group = case_when(product_gl_group %in% c("Required Setup", "Other Services") ~ "Implementation",
                      TRUE ~ as.character(product_gl_group)))
  
proj_hours_overages_core <- proj_hours_overages_pre %>% 
  group_by(group, account_region) %>% 
  summarize(
      auto_hours_ie_hour_overages = round(sum(planned_hour_overages, na.rm = TRUE), 2),
      hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
      hours_saved = round(sum(hours_saved, na.rm = TRUE), 2),
      n = n()
    )

proj_hours_overages_india <- proj_hours_overages_pre %>% 
  filter(milestone_pm_region == "NAVEX India") %>% 
  group_by(group) %>% 
  summarize(
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    hour_overages = round(sum(planned_hour_overages, na.rm = TRUE), 2),
    hours_saved = round(sum(hours_saved, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_backlog_pre <- proj_hours_backlog %>% 
  rename(
      milestone_id = Milestone_ID_18__c,
      milestone_name = Name,
      product_gl_group = Product__r.GL_Group__c,
      product_family = Product__r.Family,
      milestone_status = pse__Status__c,
      hours_completed = Total_Planned_Hours__c,
      backlog_hours = Planned_vs_Client_Billable_no_neg__c,
      milestone_pm = Milestone_PM__r.Name,
      milestone_pm_group = Milestone_PM__r.pse__Group__r.Name,
      milestone_pm_region = Milestone_PM__r.pse__Region__r.Name,
      milestone_pm_manager = Milestone_PM_s_Manager__r.Name,
      account_cso_region_bad = Account__r.Account_Owner_Region_CSO_Reporting__c,
      account_region = Account__r.Reporting_Region__c,
      go_live_date = Actual_Go_Live__c
    ) %>% 
  mutate(
    hours_completed = as.double(hours_completed),
    backlog_hours = as.double(backlog_hours),
    go_live_date = as.Date(go_live_date),
    product = case_when((grepl("EP ", product_family)|product_family == "Telephony") ~ "EthicsPoint", grepl("Policy", product_family) ~ "PolicyTech", product_family == "NG Compliance Training" ~ "NAVEXEngage", product_family == "RiskRate" ~ "RiskRate", product_family == "WhistleB" ~ "WhistleB", product_family == "ESG" ~ "ESG", product_family == "Disclosure Management" ~ "Disclosure Manager", product_family == "Lockpath" ~ "Lockpath",
                        TRUE ~ "Other"),
    group = case_when(product_gl_group %in% c("Required Setup", "Other Services") ~ "Implementation",
                      TRUE ~ as.character(product_gl_group)))

proj_hours_backlog_core <- proj_hours_backlog_pre %>% 
  group_by(group, account_region) %>% 
  summarize(
      backlog_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
      hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
      n = n()
    )

proj_hours_backlog_india <- proj_hours_backlog_pre %>% 
  filter(grepl("India", milestone_pm_region)) %>% 
  group_by(group, product) %>% 
  summarize(
    backlog_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_backlog_on_hold_core <- proj_hours_backlog_pre %>% 
  filter(milestone_status %in% "Delayed On-Hold") %>% 
  group_by(group, product) %>% 
  summarize(
    backlog_on_hold_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_backlog_on_hold_core <- proj_hours_backlog_pre %>% 
  filter(milestone_status %in% "Delayed On-Hold",
         grepl("India", milestone_pm_region)) %>% 
  group_by(group, product) %>% 
  summarize(
    backlog_on_hold_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_backlog_on_hold_india <- proj_hours_backlog_pre %>% 
  filter(milestone_status %in% "Delayed On-Hold",
         grepl("India", milestone_pm_region)) %>%
  group_by(group, product) %>% 
  summarize(
    backlog_on_hold_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )


proj_hours_backlog_pipeline_core <- proj_hours_backlog_pre %>% 
  filter(milestone_status %in% "Pipeline") %>% 
  group_by(group, product) %>% 
  summarize(
    backlog_pipeline_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )

proj_hours_backlog_pipeline_india <- proj_hours_backlog_pre %>% 
  filter(milestone_status %in% "Pipeline",
         grepl("India", milestone_pm_region)) %>%
  group_by(group, product) %>% 
  summarize(
    backlog_pipeline_hours = round(sum(backlog_hours, na.rm = TRUE), 2),
    hours_completed = round(sum(hours_completed, na.rm = TRUE), 2),
    n = n()
  )

on_time_completion_pre <- on_time_completion %>% 
  rename(
      milestone_id = Milestone_ID_18__c,
      milestone_name = Name,
      group = pse__Project__r.pse__Group__r.Name,
      product_family = Product__r.Family,
      milestone_status = pse__Status__c,
      milestone_on_time_td = Milestone_On_Time_TD__c,
      hours_completed = Total_Planned_Hours__c,
      planned_hours = pse__Planned_Hours__c,
      approved_hours = Total_Approved_Hours__c,
      backlog_hours = Planned_vs_Client_Billable_Hours__c,
      milestone_pm = Milestone_PM__r.Name,
      milestone_pm_group = Milestone_PM__r.pse__Group__r.Name,
      milestone_pm_region = Milestone_PM__r.pse__Region__r.Name,
      milestone_pm_manager = Milestone_PM_s_Manager__r.Name,
      account_cso_region_bad = Account__r.Account_Owner_Region_CSO_Reporting__c,
      account_region = Account__r.Reporting_Region__c,
      go_live_date = Actual_Go_Live__c,
      calc_duration_days = Calculated_Duration_days__c
    ) %>% 
  mutate(
    hours_completed = as.double(hours_completed),
    backlog_hours = as.double(backlog_hours),
    go_live_date = as.Date(go_live_date),
    # product = case_when((grepl("EP ", product_family)|product_family == "Telephony") ~ "EthicsPoint", grepl("Policy", product_family) ~ "PolicyTech", product_family == "NG Compliance Training" ~ "NAVEXEngage", product_family == "RiskRate" ~ "RiskRate", product_family == "WhistleB" ~ "WhistleB", product_family == "ESG" ~ "ESG", product_family == "Disclosure Management" ~ "Disclosure Manager", product_family == "Lockpath" ~ "Lockpath",
    #                     TRUE ~ "Other")
    )

on_time_completion_core <- on_time_completion_pre %>% 
  group_by(group) %>% 
  summarize(
    milestone_on_time_td = sum(milestone_on_time_td),
    count_total_milestones = n(),
    on_time_completion = round(sum(milestone_on_time_td)/n(), 2),
    time_to_implement = round(mean(calc_duration_days, na.rm = TRUE), 2),
    delivery_efficiency = round(sum(planned_hours, na.rm = TRUE)/sum(approved_hours, na.rm = TRUE), 2)
  )

on_time_completion_india <- on_time_completion_pre %>% 
  filter(grepl("India", milestone_pm_region)) %>% 
  group_by(group) %>% 
  summarize(
    milestone_on_time_td = sum(milestone_on_time_td),
    count_total_milestones = n(),
    on_time_completion = round(sum(milestone_on_time_td)/n(), 2),
    time_to_implement = round(mean(calc_duration_days, na.rm = TRUE), 2),
    delivery_efficiency = round(sum(planned_hours, na.rm = TRUE)/sum(approved_hours, na.rm = TRUE), 2)
  )

```

```{r cases_opened_closed} 
cases_pre <- cases %>% 
  rename(
    product_team = Client_Care_Team__c,
    close_date = ClosedDate,
    opened_date = CreatedDate,
    type = Record_Type__c,
    skill = Skill__c,
    reporting_region = Account.Reporting_Region__c,
    location = Owner__r.Location__c,
    owner_name = Owner__r.Name,
    case_age = Age_Days__c
  ) %>% 
     mutate(Month = floor_date(close_date, unit="month"),
            Product = case_when(
              type == "Customer Support Requests" & grepl("EthicsPoint|Telephony", product_team) ~ "EthicsPoint",
              type == "Customer Support Requests" & grepl("PolicyTech", product_team) ~ "PolicyTech",
              type == "Customer Support Requests" & grepl(" Training", product_team)~ "NAVEXEngage",
              type == "Customer Support Requests" & grepl("RiskRate", product_team) ~ "RiskRate",
              type == "Customer Support Requests" & grepl("Disclosures", product_team) ~ "Disclosures",
              type == "Customer Support Requests" & grepl("WhistleB", product_team) ~ "WhistleB",
              type == "Customer Support Requests" & grepl("ESG", product_team) ~ "ESG",
              type == "Customer Support Requests" & product_team == TRUE ~ "Other",
              type == "Discontinued Client" ~ "Discontinuation")
     )

cases_opened <- cases_pre %>% 
  filter(between(opened_date, as.Date(from_date), as.Date(to_date))) %>% 
  group_by(reporting_region, Product) %>% 
  summarize(
    cases_opened = n()
  ) %>% 
  bind_rows(
    cases_pre %>% 
      filter(between(opened_date, as.Date(from_date), as.Date(to_date))) %>%
      mutate(reporting_region = "Total") %>% 
      group_by(reporting_region, Product) %>% 
      summarize(
        cases_opened = n()
      )
  ) %>% 
  bind_cols(
    cases_pre %>% 
      filter(between(close_date, as.Date(from_date), as.Date(to_date))) %>% 
      group_by(reporting_region, Product) %>% 
      summarize(
        cases_closed = n()
    ) %>%
      bind_rows(
        cases_pre %>% 
          filter(between(close_date, as.Date(from_date), as.Date(to_date))) %>% 
          mutate(reporting_region="Total") %>%
          group_by(reporting_region, Product) %>% 
          summarize(
            cases_closed = n()
          ) 
      ) %>% select(cases_closed) 
  )
  
```


```{r case_milestones}
CMS <- cases_milestones %>% 
  rename(
    reporting_region = Case.Account.Reporting_Region__c,
    owner = Case.Owner__r.Name,
    location = Case.Owner__r.Location__c,
    close_date = Case.ClosedDate,
    skill = Case.Skill__c,
    milestone_name = MilestoneType.Name,
    product_team = Case.Client_Care_Team__c
  ) %>% 
  filter(!product_team %in% c('Lockpath', 'NetClaim'),
         !owner %in% c('Sean Brady', 'Lisa Ohland', 'Adam Rollins')) %>% 
  mutate(Month = floor_date(close_date, unit="month"),
         `Customer Success Account` = as.integer(Case.Account.Customer_Success_Account__c)) %>%
  mutate(Product = case_when(grepl("EthicsPoint", product_team) ~ "EthicsPoint",
                             grepl("PolicyTech", product_team) ~ "PolicyTech",
                             grepl("Online Training", product_team)|grepl("Compliance Training", product_team) ~ "NAVEXEngage",
                             grepl("RiskRate", product_team) ~ "RiskRate",
                             grepl("Disclosures", product_team) ~ "Disclosures",
                             grepl("WhistleB", product_team) ~ "WhistleB",
                             grepl("ESG", product_team) ~ "ESG"))

CMS_product <- CMS %>% 
  group_by(Month, Product) %>% 
  summarize(
    `Average Elapsed Time (Hours)` = mean(ElapsedTimeInHrs, na.rm = TRUE),
    `Average Elapsed Time (Days)` = mean(ElapsedTimeInDays, na.rm = TRUE),
    `Average Elapsed Time (Business Days)` = mean(ElapsedTimeInHrs/8, na.rm = TRUE),
    `Record Count` = n(),
    `Sum of Customer Success Account` = sum(`Customer Success Account`))

CMS_total <- CMS %>% 
  group_by(Month) %>% 
  summarize(Product = "Total",
            `Average Elapsed Time (Hours)` = mean(ElapsedTimeInHrs, na.rm = TRUE),
            `Average Elapsed Time (Days)` = mean(ElapsedTimeInDays, na.rm = TRUE),
            `Average Elapsed Time (Business Days)` = mean(ElapsedTimeInHrs/8, na.rm = TRUE),
            `Record Count` = n(),
            `Sum of Customer Success Account` = sum(`Customer Success Account`))
CMS_final <- bind_rows(CMS_product, CMS_total) %>% arrange(Month)

```

```{r billable_utilization}
util_pto <- util_pto %>% 
  rename(
        timecard_start_date = pse__Start_Date__c,
        timecard_end_date = pse__End_Date__c,
        timecard_status = pse__Status__c,
        timecard_total_hours = pse__Total_Hours__c,
        milestone_name = pse__Milestone__r.Name,
        resource_name = pse__Resource__r.Full_Name__c,
        resource_manager = pse__Resource__r.pse__Salesforce_User__r.Manager.Name,
        resource_group = pse__Resource__r.pse__Group__r.Name
      ) %>% 
  group_by(
    resource_name
  ) %>% 
  summarize(
    pto_hours = sum(timecard_total_hours)
  ) %>% ungroup()

util_pre <- util %>% 
  rename(
      calculation_name = Utilization_Calculation_Name__c,
      calculation_start_date = pse__Historical_Start_Date__c,
      calculation_end_date = pse__Historical_End_Date__c,
      time_period_type = pse__Utilization_Calculation__r.pse__Time_Period_Types__c,
      utilization = pse__Historical_Utilization__c,
      billable_utilization = pse__Historical_Utilization_Billable_Only__c,
      calendar_hours = pse__Historical_Calendar_Hours__c,
      billable_hours = pse__Historical_Billable_Hours__c,
      client_non_billable_hours = Historical_Client_Non_Billable__c,
      non_billable_hours = pse__Historical_Non_Billable_Hours__c,
      resource_name = pse__Resource__r.Name,
      resource_manager = pse__Resource__r.pse__Salesforce_User__r.Manager.Name,
      resource_region = pse__Resource__r.pse__Region__r.Name,
      resource_group = pse__Resource__r.pse__Group__r.Name,
      resource_start_date = pse__Resource__r.pse__Start_Date__c,
    ) %>% 
  mutate(
      utilization = round(as.double(utilization), 2),
      billable_utilization = round(as.double(billable_utilization), 2),
      calendar_hours = round(as.double(calendar_hours), 2),
      billable_hours = round(as.double(billable_hours), 2),
      client_non_billable_hours = round(as.double(client_non_billable_hours), 2),
      non_billable_hours = round(as.double(non_billable_hours), 2),
      calculation_start_date = round(as.Date(calculation_start_date), 2),
      calculation_end_date = round(as.Date(calculation_end_date), 2),
      resource_start_date = round(as.Date(resource_start_date), 2),
      resource_department = case_when(
        resource_group == "Customer Interface" ~ "Web Services",
        resource_group == "Quality Assurance" ~ "Web Services",
        TRUE ~ resource_group
      )
    )
 # Calculate Calendar Hours Delta
util_pre <- util_pre %>% 
  mutate(
      calendar_hour_delta = 
        calendar_hours - 
        billable_hours - 
        client_non_billable_hours - 
        non_billable_hours,
      calendar_hour_delta = round(calendar_hour_delta, 2)
    )

utilization <- util_pre %>% 
  left_join(util_pto, by=c("resource_name" = "resource_name")
            ) %>% 
  mutate(
      # Replace NA values with 0
      pto_hours = replace_na(pto_hours, 0),
      # Calculate Productive Utilization as new column
      productive_utilization = round(
        billable_hours / (calendar_hours - pto_hours) * 100, 3)
    )

global_pivot <- utilization %>% 
    group_by(
      resource_department
    ) %>% 
    summarise(
      billable_utilization = round(mean(billable_utilization), 0),
      productive_utilization = round(mean(productive_utilization), 0),
      n = n()
    )

us_pivot <- utilization %>% 
  filter(
    resource_region == "NAVEX US"
  ) %>% 
  group_by(
      resource_department
    ) %>% 
    summarize(
      billable_utilization = round(mean(billable_utilization), 0),
      productive_utilization = round(mean(productive_utilization), 0),
      n=n()
    )

india_pivot <- utilization %>% 
  filter(
    resource_region == "NAVEX India"
  ) %>% 
  group_by(
      resource_department
    ) %>% 
    summarize(
      billable_utilization = round(mean(billable_utilization), 0),
      productive_utilization = round(mean(productive_utilization), 0),
      n=n()
    )

eu_pivot <- utilization %>% 
  filter(
    resource_region == "NAVEX EU"
  ) %>% 
  group_by(
      resource_department
    ) %>% 
    summarize(
      billable_utilization = round(mean(billable_utilization), 0),
      productive_utilization = round(mean(productive_utilization), 0),
      n=n()
    )

utilization <- tibble(
  "Metric" = c(
    "Professional Services Billable Utilization",
    "Implementation Billable Utilization",
    "Web Services Billable Utilization",
    "Technical Specialist Billable Utilization",
    "Telecom Billable Utilization",
    "Support Billable Utilization",
    "Support Productive Utilization"
  ),
  "NG Core" = c(
      global_pivot$billable_utilization[global_pivot$resource_department=="Professional Services"],
      global_pivot$billable_utilization[global_pivot$resource_department=="Implementation"],
      global_pivot$billable_utilization[global_pivot$resource_department=="Web Services"],
      global_pivot$billable_utilization[global_pivot$resource_department=="Technical Specialist"],
      global_pivot$billable_utilization[global_pivot$resource_department=="Telecom"],
      global_pivot$billable_utilization[global_pivot$resource_department=="Customer Support"],
      global_pivot$productive_utilization[global_pivot$resource_department=="Customer Support"]
      ),
  "US" = c(
      us_pivot$billable_utilization[us_pivot$resource_department=="Professional Services"],
      us_pivot$billable_utilization[us_pivot$resource_department=="Implementation"],
      us_pivot$billable_utilization[us_pivot$resource_department=="Web Services"],
      us_pivot$billable_utilization[us_pivot$resource_department=="Technical Specialist"],
      us_pivot$billable_utilization[us_pivot$resource_department=="Telecom"],
      us_pivot$billable_utilization[us_pivot$resource_department=="Customer Support"],
      us_pivot$productive_utilization[us_pivot$resource_department=="Customer Support"]
      ),
  # "India" = c(
  #     NA,
  #     india_pivot$billable_utilization[india_pivot$resource_department=="Implementation"],
  #     NA,
  #     NA,
  #     NA,
  #     india_pivot$billable_utilization[india_pivot$resource_department=="Customer Support"],
  #     india_pivot$productive_utilization[india_pivot$resource_department=="Customer Support"]
  #     ),
  "EU"= c(
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Professional Services"],
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Implementation"],
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Web Services"],
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Technical Specialist"],
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Telecom"],
      eu_pivot$billable_utilization[eu_pivot$resource_department=="Customer Support"],
      eu_pivot$productive_utilization[eu_pivot$resource_department=="Customer Support"]
      ),
  "IRM" = c(
      global_pivot$billable_utilization[global_pivot$resource_department=="Lockpath - PS"],
      NA,
      NA,
      NA,
      NA,
      global_pivot$billable_utilization[global_pivot$resource_department=="Lockpath - CS"],
      global_pivot$productive_utilization[global_pivot$resource_department=="Lockpath - CS"]
    )
  )



```

```{r test_sample_queries}
testq <- sf_query("SELECT Name, pse__Monday_Hours__c, pse__Tuesday_Hours__c, pse__Wednesday_Hours__c, pse__Thursday_Hours__c, pse__Friday_Hours__c, pse__Week_Total_Hours__c FROM pse__Work_Calendar__c")
testq2 <- sf_query("SELECT Id, pse__Region__r.Name, pse__Salesforce_User__r.Id, Name FROM Contact WHERE pse__Is_Resource__c = TRUE and pse__Is_Resource_Active__c = TRUE") 
test_df <- testq2 %>% 
  inner_join(testq, by = join_by(pse__Salesforce_User__r.Id == Id)) %>% 
  filter(Location__c == 'US', pse__Region__r.Name == 'NAVEX EU')
test_df
```
```